server:
  port: 8004

spring:
  application:
    name: cloud-payment-service
  datasource:
    druid:
      db-type: com.aliaba.druid.pool.DruidDataSource
      url: jdbc:mysql://192.168.32.147:3306/db2019?useUnicode=true&charEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: org.gjt.mm.mysql.Driver
  cloud:
    zookeeper:
      connect-string: 192.168.32.149:2181
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.guigu.springcloud.entity
